; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName            "Nickvision Parabolic"
#define MyAppShortName       "Parabolic"
#define MyAppShortNameLower  "parabolic"
#define MyAppVersion         "2026.8.5"
#define MyAppPublisher       "Nickvision"
#define MyAppURL             "https://nickvision.org"
#define MyAppExeName         "Nickvision.Parabolic.WinUI.exe"
#define StartYearCopyright   "2021"
#define CurrentYear          GetDateTimeString('yyyy','','')

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{F0AE5CF5-E5D8-45DA-BE26-292D04C2591B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}

AppCopyright={#StartYearCopyright}-{#CurrentYear}  {#MyAppPublisher}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}

VersionInfoDescription={#MyAppName} installer
VersionInfoProductName={#MyAppName}
VersionInfoVersion={#MyAppVersion}

UninstallDisplayName={#MyAppName} {#MyAppVersion}
UninstallDisplayIcon={app}\Release\{#MyAppExeName}
AppPublisher={#MyAppPublisher}

ShowLanguageDialog=yes
UsePreviousLanguage=no
LanguageDetectionMethod=uilanguage

ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

WizardStyle=modern dynamic windows11
WizardResizable=yes
WizardSizePercent=120,130

DefaultDirName={autopf}\{#MyAppName}
LicenseFile=..\License.rtf
OutputDir=..\inno
OutputBaseFilename=NickvisionParabolicSetup
SetupIconFile=..\resources\org.nickvision.tubeconverter.ico
Compression=lzma
SolidCompression=yes
PrivilegesRequired=admin
CloseApplications=yes
RestartIfNeededByRun=no

[Languages]
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"
Name: "czech"; MessagesFile: "compiler:Languages\Czech.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "hungarian"; MessagesFile: "compiler:Languages\Hungarian.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "slovak"; MessagesFile: "compiler:Languages\Slovak.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "tamil"; MessagesFile: "compiler:Languages\Tamil.isl"

[InstallDelete]
Type: filesandordirs; Name: "{app}\*"

[UninstallDelete]
Type: filesandordirs; Name: "{app}"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "yt-dlp.exe"; DestDir: "{app}\Release"; Flags: ignoreversion
Source: "aria2c.exe"; DestDir: "{app}\Release"; Flags: ignoreversion
Source: "ffmpeg.exe"; DestDir: "{app}\Release"; Flags: ignoreversion
Source: "ffplay.exe"; DestDir: "{app}\Release"; Flags: ignoreversion
Source: "ffprobe.exe"; DestDir: "{app}\Release"; Flags: ignoreversion
Source: "deno.exe"; DestDir: "{app}\Release"; Flags: ignoreversion
Source: "N_m3u8DL-RE.exe"; DestDir: "{app}\Release"; Flags: ignoreversion
Source: "..\resources\licenses\N_m3u8DL-RE-LICENSE.txt"; DestDir: "{app}\Release"; Flags: ignoreversion
Source: "..\{#GetEnv('APP_FILES_PATH')}\{#MyAppExeName}"; DestDir: "{app}\Release"; Flags: ignoreversion
Source: "..\{#GetEnv('APP_FILES_PATH')}\*"; DestDir: "{app}\Release"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\{#GetEnv('NATIVE_HOST_FILES_PATH')}\*"; DestDir: "{app}\Release"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\{#GetEnv('DOWNLOAD_SERVICE_FILES_PATH')}\*"; DestDir: "{app}\Release"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppShortName}"; Filename: "{app}\Release\{#MyAppExeName}"; Tasks: quicklaunchicon
Name: "{commondesktop}\{#MyAppShortName}"; Filename: "{app}\Release\{#MyAppExeName}"; Tasks: desktopicon

[Registry]
Root: HKCR; Subkey: {#MyAppShortNameLower}; ValueType: "string"; ValueData: "URL:Custom Protocol"; Flags: uninsdeletekey
Root: HKCR; Subkey: {#MyAppShortNameLower}; ValueType: "string"; ValueName: "URL Protocol"; ValueData: ""
Root: HKCR; Subkey: "{#MyAppShortNameLower}\DefaultIcon"; ValueType: "string"; ValueData: "{app}\Release\{#MyAppExeName},0"
Root: HKCR; Subkey: "{#MyAppShortNameLower}\shell\open\command"; ValueType: "string"; ValueData: """{app}\Release\{#MyAppExeName}"" ""%1"""
Root: HKLM64; Subkey: "Software\Mozilla\NativeMessagingHosts\com.nickvision.parabolic"; ValueType: "string"; ValueData: "{app}\Release\com.nickvision.parabolic.json"; Flags: uninsdeletekey
Root: HKLM32; Subkey: "Software\Mozilla\NativeMessagingHosts\com.nickvision.parabolic"; ValueType: "string"; ValueData: "{app}\Release\com.nickvision.parabolic.json"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: "string"; ValueName: "Parabolic Download Service"; ValueData: """{app}\Release\Nickvision.Parabolic.DownloadService.exe"" --background"; Flags: uninsdeletevalue

[Run]
Filename: "{app}\Release\Nickvision.Parabolic.DownloadService.exe"; Parameters: "--background"; Flags: nowait runhidden skipifsilent runascurrentuser
Filename: "{app}\Release\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent unchecked

[Code]
procedure StopPersistentDownloadService;
var
  ResultCode: Integer;
begin
  Exec(ExpandConstant('{sys}\taskkill.exe'),
    '/F /IM Nickvision.Parabolic.DownloadService.exe',
    '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  StopPersistentDownloadService;
  Result := '';
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usUninstall then
  begin
    StopPersistentDownloadService;
  end;
end;

procedure WriteFirefoxNativeHostManifest;
var
  HostPath: String;
  EscapedHostPath: String;
  Manifest: String;
begin
  HostPath := ExpandConstant('{app}\Release\Nickvision.Parabolic.NativeHost.exe');
  EscapedHostPath := HostPath;
  StringChangeEx(EscapedHostPath, '\', '\\', True);
  Manifest := '{' + #13#10 +
    '  "name": "com.nickvision.parabolic",' + #13#10 +
    '  "description": "Parabolic Firefox Native Messaging bridge",' + #13#10 +
    '  "path": "' + EscapedHostPath + '",' + #13#10 +
    '  "type": "stdio",' + #13#10 +
    '  "allowed_extensions": ["parabolic-media-detector@othmanbenbrahim.dev"]' + #13#10 +
    '}' + #13#10;
  if not SaveStringToFile(ExpandConstant('{app}\Release\com.nickvision.parabolic.json'), Manifest, False) then
  begin
    RaiseException('Unable to create the Firefox Native Messaging host manifest.');
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    WriteFirefoxNativeHostManifest;
  end;
end;
